### ISSUE TITLE
[New Feature]: Update ops procedure for smoke test (golden data)

### ISSUE THREAD

**Issue by riverma** [nasa/opera-sds-ops#12]
### Checked for duplicates

Yes - I've already checked

### Alternatives considered

Yes - and alternatives don't suffice

### Related problems

- PCM RC-6 removed an ISL
- The current ops guide procedure for the smoke test is a bit confusing for novices

### Describe the feature request

The Ops Guide could benefit from the following:
- Removal of all ISL references in lieu of [PCM RC-6](https://github.com/nasa/opera-sds-pcm/releases/tag/1.0.0-rc.6.0)
- Leveraging the Standardized page template discussed in https://github.com/nasa/opera-sds-ops/issues/8
- Being specific about how to compare the output products generated using the `dswx_compare.py` script - i.e. there will be some differences like date fields, etc., what do we expect the success criteria to be exactly when running this script?

**Comment by niarenaw** [comment]
The procedure has been updated to reflect the desired feature requests.

**Comment by riverma** [comment]
Just had a chance to review the Wiki entry for this. Looks great @niarenaw - thank you!
