### ISSUE TITLE
[New Feature]: Ops team executing E2E testing for R1-RC5

### ISSUE THREAD

**Issue by LucaCinquini** [nasa/opera-sds-ops#7]
### Checked for duplicates

Yes - I've already checked

### Alternatives considered

Yes - and alternatives don't suffice

### Describe the feature request

I suggest that we make sure that the ops team is able to execute the Release 1 processing with the latest stable release. To this point, sometimes in the next couple of weeks:
o Can Phil deploy R1-RC5 to the I&T venue?
o Can Lala and Sri execute the standard regression test suite, documenting the operations and result?

**Comment by philipjyoon** [comment]
R1-RC5 has been deployed to I&T FWD and the system has been smoke tested. Lala will clear up the system and run regression - I will help as needed.

**Comment by LucaCinquini** [comment]
Sri executed the test using R1-RC5 and captured the results in this wiki page:

https://wiki.jpl.nasa.gov/pages/viewpage.action?pageId=671764746

Closing.
